// Generated by CoffeeScript 2.7.0
import {
  FAILSAFE_SCHEMA,
  JSON_SCHEMA,
  dump,
  load
} from '../index';

require('../index');

module.exports = require('../index');

({
  onwarning: function(except) {
    return console.log(`${except.name} -- ${except.message}`);
  }
});

module.exports.loadJson = function(text) {
  var options;
  options = {
    schema: JSON_SCHEMA,
    json: true,
    onWarning: onwarning
  };
  return load(text, options);
};

module.exports.loadJsonFromFile = async function(path) {
  var fc, fd;
  fd = (await open(path, 'r'));
  fc = fd.createReadStream();
  return loadJson(fc);
};

module.exports.loadYaml = function(text) {
  var options;
  options = {
    schema: FAILSAFE_SCHEMA,
    json: false,
    onWarning: onwarning
  };
  return load(text, options);
};

module.exports.loadFromFile = async function(path) {
  var fc, fd;
  fd = (await open(path, 'r'));
  fc = fd.createReadStream();
  return loadYaml(fc);
};

module.exports.toFile = async function(yaml_obj, path) {
  var fc, fd, options;
  options = {
    schema: FAILSAFE_SCHEMA
  };
  fd = (await open(path, 'w'));
  return fc = fd.createWriteStream(dump(yaml_obj, options));
};
